version: 2.1

workflows:
  version: 2
  commit:
    jobs:
      - test_1
     # - deploy
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * 20 *"
          filters:
            branches:
              only:
                - master
               # - beta
    jobs:
      - test_1
      - coverage
In the above example, the commit workflow has no triggers key and will run on every git push. The nightly workflow has a triggers key and will run on the specified schedule.

Specifying a Valid

jobs:
  #build:
  test_1:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
                                # https://circleci.com/docs/2.0/hello-world/
